### ISSUE TITLE
Google font is missing

### ISSUE THREAD

**Issue by briannaneet** [briannaneet/events-calendar#1]
@muxlowc 

Everything looks good in Markbot except I keep getting the error "The Google font, Merriweather, (regular, italic and bold) is missing" although I've linked it in my index head with both 400, 400i and 700 styles. In my main.css, I've also tried it with and without single quotations.

**Comment by muxlowc** [comment]
@briannaneet  hmm this seems to be happening due to an update on google fonts. Try mine:

 ` <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">`

Your css looks good, so hopefully using the above in your html instead will work :)

**Comment by briannaneet** [comment]
It worked, thank you so much :)
